### PR TITLE
add the possibility to use a custom logger class

### PR DESCRIPTION
**Pull request by CyrilP**

### CODE REVIEW

**Comment by donbeave** [comment]
@gavlyukovskiy Hi! When are you planning to release this feature?

**Comment by gavlyukovskiy** [comment]
@donbeave I was short on time lately, I'll try to do the release in couple of days.

**Comment by gavlyukovskiy** [comment]
@donbeave new version 1.6.2 is available in maven central

**Comment by donbeave** [comment]
Thank you!

**Pull request merged**
